apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always

  # Para entrar no pod, execute o comando: kubectl exec --stdin --tty ubuntu -- /bin/bash
  # Para instalar libs, execute antes:
    # apt-get update -y
  
  # Para instalar libs básicas de debugging de rede, execute:
    # apt-get install -y iputils-ping
    # apt-get install traceroute